---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginxlb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginxlb
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginxlb
  replicas: 1 # number of replica
  template:
    metadata:
      labels:
        app: nginxlb
    spec:
      containers:
      - name: nginxlb
        image: nginx:1.7.9
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
