---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc2
  labels:
    app: nginxlb2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginxlb2
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  selector:
    matchLabels:
      app: nginxlb2
  replicas: 1 # number of replica
  template:
    metadata:
      labels:
        app: nginxlb2
    spec:
      containers:
      - name: nginxlb2
        image: nginx:1.7.9
        ports:
        - containerPort: 80