apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-scale
  labels:
    app: nginxtest
  annotations:
    monitoring: "true"
spec:
  replicas: 25
  selector:
    matchLabels:
      app: nginxtest
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginxservice
  name: nginxservice
spec:
  ports:
    - port: 80
  selector:
    app: nginxtest
  type: LoadBalancer
