---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-standard
  
---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-svc
  labels:
    app: aspnet-app
spec:
  ports:
  - port: 80
    name: aspnetpvc
  clusterIP: None
  selector:
    app: aspnet-app
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: aspnetpvc
  labels:
    app: aspnet-app
spec:
  serviceName: aspnet-svc
  selector:
    matchLabels:
      app: aspnet-app
  replicas: 1 # number of replica
  template:
    metadata:
      labels:
        app: aspnet-app
    spec:
      containers:
      - name: aspnet-azuredisk
        image: mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
        volumeMounts:
        - name: disk01
          mountPath: 'D:'
      nodeSelector:
        beta.kubernetes.io/os: windows
      volumes:
      - name: disk01
        persistentVolumeClaim:
          claimName: pvc-azuredisk